Bug: Fix _event_collector_ref bug introduced from 93e6604092
During worker startup and receive launch_builtin_model concurrently, there were error log:

2024-08-20 02:41:08,327 xinference.core.worker 7 ERROR Connected to supervisor as a fresh worker
2024-08-20 02:41:08,327 xinference.core.worker 7 ERROR [request 4578fdd8-5e5d-11ef-bddf-0ecc93937455] Enter launch_builtin_model, args: ...
2024-08-20 02:41:08,327 xinference.core.worker 7 ERROR report_event error: 'WorkerActor' object has no attribute '_event_collector_ref